export const codes = [
  { code: "+93", title: "Afghanistan" },
  { code: "+358", title: "Aland Islands" },
  { code: "+355", title: "Albania" },
  { code: "+213", title: "Algeria" },
  { code: "+1684", title: "AmericanSamoa" },
  { code: "+376", title: "Andorra" },
  { code: "+244", title: "Angola" },
  { code: "+1264", title: "Anguilla" },
  { code: "+672", title: "Antarctica" },
  { code: "+1268", title: "Antigua and Barbuda" },
  { code: "+54", title: "Argentina" },
  { code: "+374", title: "Armenia" },
  { code: "+297", title: "Aruba" },
  { code: "+61", title: "Australia" },
  { code: "+43", title: "Austria" },
  { code: "+994", title: "Azerbaijan" },
  { code: "+1242", title: "Bahamas" },
  { code: "+973", title: "Bahrain" },
  { code: "+880", title: "Bangladesh" },
  { code: "+1246", title: "Barbados" },
  { code: "+32", title: "Belgium" },
  { code: "+501", title: "Belize" },
  { code: "+229", title: "Benin" },
  { code: "+1441", title: "Bermuda" },
  { code: "+975", title: "Bhutan" },
  { code: "+591", title: "Bolivia, Plurinational State of" },
  { code: "+387", title: "Bosnia and Herzegovina" },
  { code: "+267", title: "Botswana" },
  { code: "+55", title: "Brazil" },
  { code: "+246", title: "British Indian Ocean Territory" },
  { code: "+673", title: "Brunei Darussalam" },
  { code: "+359", title: "Bulgaria" },
  { code: "+226", title: "Burkina Faso" },
  { code: "+257", title: "Burundi" },
  { code: "+855", title: "Cambodia" },
  { code: "+237", title: "Cameroon" },
  { code: "+1", title: "Canada" },
  { code: "+238", title: "Cape Verde" },
  { code: "+345", title: "Cayman Islands" },
  { code: "+236", title: "Central African Republic" },
  { code: "+235", title: "Chad" },
  { code: "+56", title: "Chile" },
  { code: "+86", title: "China" },
  { code: "+61", title: "Christmas Island" },
  { code: "+61", title: "Cocos (Keeling) Islands" },
  { code: "+57", title: "Colombia" },
  { code: "+269", title: "Comoros" },
  { code: "+242", title: "Congo" },
  { code: "+682", title: "Cook Islands" },
  { code: "+506", title: "Costa Rica" },
  { code: "+385", title: "Croatia" },
  { code: "+357", title: "Cyprus" },
  { code: "+420", title: "Czech Republic" },
  { code: "+45", title: "Denmark" },
  { code: "+253", title: "Djibouti" },
  { code: "+1767", title: "Dominica" },
  { code: "+1849", title: "Dominican Republic" },
  { code: "+593", title: "Ecuador" },
  { code: "+20", title: "Egypt" },
  { code: "+503", title: "El Salvador" },
  { code: "+240", title: "Equatorial Guinea" },
  { code: "+291", title: "Eritrea" },
  { code: "+372", title: "Estonia" },
  { code: "+251", title: "Ethiopia" },
  { code: "+500", title: "Falkland Islands (Malvinas)" },
  { code: "+298", title: "Faroe Islands" },
  { code: "+679", title: "Fiji" },
  { code: "+358", title: "Finland" },
  { code: "+33", title: "France" },
  { code: "+594", title: "French Guiana" },
  { code: "+689", title: "French Polynesia" },
  { code: "+241", title: "Gabon" },
  { code: "+220", title: "Gambia" },
  { code: "+995", title: "Georgia" },
  { code: "+49", title: "Germany" },
  { code: "+233", title: "Ghana" },
  { code: "+350", title: "Gibraltar" },
  { code: "+30", title: "Greece" },
  { code: "+299", title: "Greenland" },
  { code: "+1473", title: "Grenada" },
  { code: "+590", title: "Guadeloupe" },
  { code: "+1671", title: "Guam" },
  { code: "+502", title: "Guatemala" },
  { code: "+44", title: "Guernsey" },
  { code: "+224", title: "Guinea" },
  { code: "+245", title: "Guinea-Bissau" },
  { code: "+595", title: "Guyana" },
  { code: "+509", title: "Haiti" },
  { code: "+379", title: "Holy See (Vatican City State)" },
  { code: "+504", title: "Honduras" },
  { code: "+852", title: "Hong Kong" },
  { code: "+36", title: "Hungary" },
  { code: "+354", title: "Iceland" },
  { code: "+91", title: "India" },
  { code: "+62", title: "Indonesia" },
  { code: "+353", title: "Ireland" },
  { code: "+44", title: "Isle of Man" },
  { code: "+972", title: "Israel" },
  { code: "+39", title: "Italy" },
  { code: "+1876", title: "Jamaica" },
  { code: "+81", title: "Japan" },
  { code: "+44", title: "Jersey" },
  { code: "+962", title: "Jordan" },
  { code: "+77", title: "Kazakhstan" },
  { code: "+254", title: "Kenya" },
  { code: "+686", title: "Kiribati" },
  { code: "+82", title: "Korea, Republic of South Korea" },
  { code: "+965", title: "Kuwait" },
  { code: "+996", title: "Kyrgyzstan" },
  { code: "+856", title: "Laos" },
  { code: "+371", title: "Latvia" },
  { code: "+961", title: "Lebanon" },
  { code: "+266", title: "Lesotho" },
  { code: "+218", title: "Libyan Arab Jamahiriya" },
  { code: "+423", title: "Liechtenstein" },
  { code: "+370", title: "Lithuania" },
  { code: "+352", title: "Luxembourg" },
  { code: "+853", title: "Macao" },
  { code: "+389", title: "Macedonia" },
  { code: "+261", title: "Madagascar" },
  { code: "+265", title: "Malawi" },
  { code: "+60", title: "Malaysia" },
  { code: "+960", title: "Maldives" },
  { code: "+223", title: "Mali" },
  { code: "+356", title: "Malta" },
  { code: "+692", title: "Marshall Islands" },
  { code: "+596", title: "Martinique" },
  { code: "+222", title: "Mauritania" },
  { code: "+230", title: "Mauritius" },
  { code: "+262", title: "Mayotte" },
  { code: "+52", title: "Mexico" },
  { code: "+691", title: "Micronesia, Federated States of Micronesia" },
  { code: "+373", title: "Moldova" },
  { code: "+377", title: "Monaco" },
  { code: "+976", title: "Mongolia" },
  { code: "+382", title: "Montenegro" },
  { code: "+1664", title: "Montserrat" },
  { code: "+212", title: "Morocco" },
  { code: "+258", title: "Mozambique" },
  { code: "+95", title: "Myanmar" },
  { code: "+264", title: "Namibia" },
  { code: "+674", title: "Nauru" },
  { code: "+977", title: "Nepal" },
  { code: "+31", title: "Netherlands" },
  { code: "+599", title: "Netherlands Antilles" },
  { code: "+687", title: "New Caledonia" },
  { code: "+64", title: "New Zealand" },
  { code: "+505", title: "Nicaragua" },
  { code: "+227", title: "Niger" },
  { code: "+234", title: "Nigeria" },
  { code: "+683", title: "Niue" },
  { code: "+672", title: "Norfolk Island" },
  { code: "+1670", title: "Northern Mariana Islands" },
  { code: "+47", title: "Norway" },
  { code: "+968", title: "Oman" },
  { code: "+92", title: "Pakistan" },
  { code: "+680", title: "Palau" },
  { code: "+970", title: "Palestinian Territory, Occupied" },
  { code: "+507", title: "Panama" },
  { code: "+675", title: "Papua New Guinea" },
  { code: "+595", title: "Paraguay" },
  { code: "+51", title: "Peru" },
  { code: "+63", title: "Philippines" },
  { code: "+872", title: "Pitcairn" },
  { code: "+48", title: "Poland" },
  { code: "+351", title: "Portugal" },
  { code: "+1939", title: "Puerto Rico" },
  { code: "+974", title: "Qatar" },
  { code: "+40", title: "Romania" },
  { code: "+7", title: "Russia" },
  { code: "+250", title: "Rwanda" },
  { code: "+262", title: "Reunion" },
  { code: "+590", title: "Saint Barthelemy" },
  { code: "+290", title: "Saint Helena, Ascension and Tristan Da Cunha" },
  { code: "+1869", title: "Saint Kitts and Nevis" },
  { code: "+1758", title: "Saint Lucia" },
  { code: "+590", title: "Saint Martin" },
  { code: "+508", title: "Saint Pierre and Miquelon" },
  { code: "+1784", title: "Saint Vincent and the Grenadines" },
  { code: "+685", title: "Samoa" },
  { code: "+378", title: "San Marino" },
  { code: "+239", title: "Sao Tome and Principe" },
  { code: "+966", title: "Saudi Arabia" },
  { code: "+221", title: "Senegal" },
  { code: "+381", title: "Serbia" },
  { code: "+248", title: "Seychelles" },
  { code: "+232", title: "Sierra Leone" },
  { code: "+65", title: "Singapore" },
  { code: "+421", title: "Slovakia" },
  { code: "+386", title: "Slovenia" },
  { code: "+677", title: "Solomon Islands" },
  { code: "+252", title: "Somalia" },
  { code: "+27", title: "South Africa" },
  { code: "+500", title: "South Georgia and the South Sandwich Islands" },
  { code: "+34", title: "Spain" },
  { code: "+94", title: "Sri Lanka" },
  { code: "+597", title: "Suriname" },
  { code: "+47", title: "Svalbard and Jan Mayen" },
  { code: "+268", title: "Swaziland" },
  { code: "+46", title: "Sweden" },
  { code: "+41", title: "Switzerland" },
  { code: "+886", title: "Taiwan" },
  { code: "+992", title: "Tajikistan" },
  { code: "+255", title: "Tanzania, United Republic of Tanzania" },
  { code: "+66", title: "Thailand" },
  { code: "+670", title: "Timor-Leste" },
  { code: "+228", title: "Togo" },
  { code: "+690", title: "Tokelau" },
  { code: "+676", title: "Tonga" },
  { code: "+1868", title: "Trinidad and Tobago" },
  { code: "+216", title: "Tunisia" },
  { code: "+90", title: "Turkey" },
  { code: "+993", title: "Turkmenistan" },
  { code: "+1649", title: "Turks and Caicos Islands" },
  { code: "+688", title: "Tuvalu" },
  { code: "+256", title: "Uganda" },
  { code: "+380", title: "Ukraine" },
  { code: "+971", title: "United Arab Emirates" },
  { code: "+44", title: "United Kingdom" },
  { code: "+1", title: "United States" },
  { code: "+598", title: "Uruguay" },
  { code: "+998", title: "Uzbekistan" },
  { code: "+678", title: "Vanuatu" },
  { code: "+58", title: "Venezuela, Bolivarian Republic of Venezuela" },
  { code: "+84", title: "Vietnam" },
  { code: "+1284", title: "Virgin Islands, British" },
  { code: "+1340", title: "Virgin Islands, U.S." },
  { code: "+681", title: "Wallis and Futuna" },
  { code: "+967", title: "Yemen" },
  { code: "+260", title: "Zambia" },
];
