name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'executing remote ssh commands using password'
        uses: appleboy/ssh-action@master
        with:
          host: '${{ secrets.HOST }}'
          password: '${{ secrets.PASSWORD }}'
          username: '${{ secrets.USERNAME }}'
          script: sh /root/update-esoque-frontend.sh